/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 */

#include <stdint.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif



int main(void)
{
    uint32_t *pAdcClrReg  = (uint32_t*)0x40012004;
    uint32_t *pRccApb2Enr = (uint32_t*)0x40023844;

    //1. enable the particular clock
    *pRccApb2Enr |= (1<<8);

    //2. change in adc control register
    *pAdcClrReg |= (1<<8);

	for(;;);
}
